# Generated by Django 2.2.20 on 2021-05-22 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210522_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.CharField(default='/some/default/link/to/a/video/', max_length=255),
        ),
    ]
