# Generated by Django 3.2.6 on 2021-08-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_videos_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
