# Generated by Django 3.2.6 on 2021-08-24 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_settings_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='display_name',
            field=models.CharField(default='Not Assigned', max_length=255),
        ),
    ]
